version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Expose port 80 for external access
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend # Path to your Streamlit app's Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    expose:
      - "8501" # Expose the internal port for communication with NGINX
    networks:
      - app_network

  backend:
    build:
      context: ./backend # Path to your FastAPI app's Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
    expose:
      - "8000" # Expose the internal port for communication with NGINX
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
